### ISSUE TITLE
Fluid transfer doesn't work

### ISSUE THREAD

**Issue by AbacusOperator** [Buuz135/Portality#100]
**Versions of relevant software**:
Minecraft 1.16.5
Forge 36.0.1
Titanium 3.2.5
Portality 3.2.0

**Issue**:
Fluid transfer between fluid modules (from input mode module to output module) of two connected portals is not working.

**Comment by Tander** [comment]
Is it why a recipe of fluid module is disabled?
![изображение](https://user-images.githubusercontent.com/1059805/110796295-db385f80-8288-11eb-8a89-28d4878180bb.png)
