### ISSUE TITLE
Item module isn't transporting items in 1.16.5

### ISSUE THREAD

**Issue by fred0plays** [Buuz135/Portality#105]
Hi, i recently downloaded enigmatica 6 update with Portality in it and i found out that item modules are not working, they are never transporting items (even if set up correctly). I watched lot of videos and tutorials and did the same thing, tried different sizes and nothing worked (on singleplayer and multiplayer).

titanium version: 1.16.5-3.2.8.2
Portality version: 1.16.4-3.2.1

**Comment by Buuz135** [comment]
Fixed in 6a629db37e8ff086c6b22c8978118be2189e8849
