### ISSUE TITLE
No Portals in Portal List

### ISSUE THREAD

**Issue by ChubbiestThread** [Buuz135/Portality#106]
I've BUILT 2 portals. They are ONLINE. I used the creative tool to make them work without power. 

NOTHING

SHOWS 

UP

IN

THE

LIST

This is the most INFURIATING thing. It works for our server admin just fine, but somehow, anyone not admin can't call portals. I'm using the version for 1.12.2. I am GOING to shoot myself.

**Comment by eeyek** [comment]
Happens to me aswell, no clue what causes it

**Comment by Buuz135** [comment]
Portals have a distance limit, make it deeper to get more distance or add an interdimensional module
