### ISSUE TITLE
Portals Not Teleporting

### ISSUE THREAD

**Issue by 123ChrisIsMe** [Buuz135/Portality#107]
Running this a free Aternos server with a couple of other low-impact building mods. The portals work, as in the flat particles in the side of the teleporter show up and you can press dial/dial once/force, but they don't actually do anything (1.16.5). We have updated forge, the servers forge and re-downloaded the mod to no avail.

**Comment by Buuz135** [comment]
pupnewfster pr'd some teleporting changes can you check when the new version is out
