### ISSUE TITLE
Long range Portality Portal causes random crashes when going through them

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/Portality#109]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3366

Mod version: portality-1.16.4-3.2.2

> 
> ### Modpack Version
> 
> [0.5.14]
> ### Describe your issue.
> 
> Sometimes when going through Portality Portal it just crashes the game. Happend to me and few other friends few times in like hour or so. There is fair bit of a distance bettwen them (like 125km) so this could be something but. Worth reporting right :D?
> ### Crash Report
> 
> https://paste.ee/p/utsCN
> ### Latest Log
> 
> _No response_
> ### Have you modified the modpack?
> 
> No
> ### User Modifications
> 
> _No response_
> ### Did the issue happen in singleplayer or on a server?
> 
> Server

**Comment by Buuz135** [comment]
pupnewfster pr'd some teleporting changes can you check when the new version is out
