### ISSUE TITLE
ATM6 -Total crash useing the Portality 

### ISSUE THREAD

**Issue by Takashi86** [Buuz135/Portality#110]
A player has put up a portal from the mod @Portality and every time someone get into render distance of it, it total crashed your game.
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Rendering Block Entity
Exit Code: -1

I play on a server where this happens. 
I have tried this 3 times now and every time it totally crashes. I know this has happened to a friend of mine that I play with and of cause other players to.
Staff had to spawn us all back at spawn before we could log back into the server.

Staff had to whip the end DIM. for now

**Comment by Buuz135** [comment]
Thats not a crashlog that can help me

**Comment by Buuz135** [comment]
pupnewfster pr'd some teleporting changes can you check when the new version is out
