### ISSUE TITLE
Client crashes when closing or destroying a portal, and modules dont work cross dimension

### ISSUE THREAD

**Issue by xamareik** [Buuz135/Portality#117]
https://pastebin.com/VdjHWYv3

Every time I close a portal or destroy it, my client crashes, and I have to restart Minecraft. Modules also won't work across dimensions. 
One portal is in a galacticraft space base, and the other is on the galacticraft moon.

**Comment by xamareik** [comment]
Having subtitles on causes this

**Comment by Buuz135** [comment]
I can't replicate this issues
