### ISSUE TITLE
Going through portals crashes the game

### ISSUE THREAD

**Issue by 2aphids** [Buuz135/Portality#124]
Going through portals crashes the game, reopening the world finds me at the other portal.

Crash log:
https://bytebin.lucko.me/jza3pPIE5W

I've tried using /forceload to see if it's related to chunk loading but nothing changes.

**Comment by 2aphids** [comment]
Other entities can go through the portals, it's only when I go through the portal myself.

**Comment by fineryx** [comment]
I have the same issue, but it works sometimes for me

**Comment by vizthex123** [comment]
Same here, I'm on the 1.18.2 version.

**Comment by Buuz135** [comment]
Can I get the crashlog? The link doesnt seem to work anymore

**Comment by fineryx** [comment]
Doesn't seem to fix the issue, still crashes
Crash log: https://paste.ee/p/AHGii
