### ISSUE TITLE
[1.18.2] Connected textures don't work

### ISSUE THREAD

**Issue by vizthex123** [Buuz135/Portality#125]
As seen in the picture, the connected textures don't unify properly, and it looks kind of bad.

![image](https://user-images.githubusercontent.com/31721920/174425630-84d3c826-9007-4dfb-a186-ba5e16f1d3e2.png)

**Comment by Buuz135** [comment]
Doi you have optifine?

**Comment by vizthex123** [comment]
No, and the textures fixed themselves when I reloaded the world.

I ended up removing the mod since it crashes the game whenever I use a portal though, which kind of defeats the purpose of the mod. Hope that gets fixed soon.

**Comment by Buuz135** [comment]
https://github.com/InnovativeOnlineIndustries/Portality/commit/b24fbf913ee8136ff8ed09b8df62d3f19d1f3df6
