### ISSUE TITLE
Error during the forge loading process

### ISSUE THREAD

**Issue by RedstonePfalz** [Buuz135/Portality#130]
Hello,
When I start Forge with Portality version 3.3.5, the following error message always appears:
`java.lang.NoClassDefFoundError: com/hrznstudio/titanium/module/ModuleController`
What can I do?

MC-Version: 1.18.2
Forge Version: 40.1.85
OS: Windows 10

[Crash-Log](https://github.com/InnovativeOnlineIndustries/Portality/files/10047937/crash-2022-11-19_21.52.26-fml.txt)

**Comment by Buuz135** [comment]
Update or add Titanium
