### ISSUE TITLE
Can connect Immersive Engineering connector to Portal Controller block

### ISSUE THREAD

**Issue by rckymtnrfc** [Buuz135/Portality#17]
Normally, to attach an Immersive Engineering connector to a block with a GUI, you can shift click to prevent the GUI from opening.  Unfortunately, that doesn't seem to happen with the Portal Controller block and the GUI still opens.

Obvious work around it just to put an IE capacitor next to the Portal Controller but I thought you'd like to know.

Thanks!

**Comment by Buuz135** [comment]
Oh yeah, it was kinda of a hack that I needed to do to use Shift+Right click with an item to change the icon of the portal. I will try to work around it.
