### ISSUE TITLE
Server Crash - Exception in server tick loop  java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n

### ISSUE THREAD

**Issue by rckymtnrfc** [Buuz135/Portality#18]
Updated to 1.0.2-3 and I'm seeing the following crash on the server.  Forge 2652.

https://pastebin.com/aT2TuSFS

**Comment by futuristickirito** [comment]
Is there a way to fix this or what?

**Comment by Buuz135** [comment]
Update the mod?
