### ISSUE TITLE
Small Bugs While Testing

### ISSUE THREAD

**Issue by FallenEagle1** [Buuz135/Portality#19]
Couple small bugs while testing. If you want this broken up into multiple issues I can do that also.
This is in the atm3 modpack
Mod Version: 1.0.3-4

1. I was testing out the energy modules and found that you cannot pull power out of the output. I used fluxducts, but tested a number of different versions of ducts/conduits and nothing worked. (There's a pic of setup below)

2. Found that you can break the all the blocks with your hand instantly and they will not drop. If you break them with a pickaxe it is still pretty instant, but the block will drop.

3. This is more something I found interesting and was guessing it wasn't intended (new feature!) but the frames of the portal can be shared by the one next to it.

Picture:
![2018-04-08_22 05 51](https://user-images.githubusercontent.com/22630113/38479053-146cbf70-3b7a-11e8-994e-f68a3876cd2c.png)

**Comment by Buuz135** [comment]
I will leave #3 I dont really mind, everything else I just fixed it
