### ISSUE TITLE
[ISSUE] Rendering Issue with OpenBlocks's Sky Block

### ISSUE THREAD

**Issue by RODragon** [Buuz135/Portality#20]
ModPack: All the Mods 3 v5.9.3
Forge Version: 2654
OpenBlocks Version: 1.12.2-1.7.6
Portality Version: 1.12.2-1.0.4-6
Tested on Java version 1.8.0_25 (Curse Default), 1.8.0_131, and 1.8.0_162

It appears that the rendering of the moving texture is affected by the rendering of Open Blocks's Sky Block in some weird ways, as seen in the image below.

![2018-04-14_15 34 24](https://user-images.githubusercontent.com/5299106/38772003-20172358-3ffb-11e8-8ac4-09e4c69f2baf.png)

After doing a bit of fiddling with it, I have noticed the rendering for the portal returns to normal when the sky block is no longer in rendering view.

![2018-04-14_15 34 35](https://user-images.githubusercontent.com/5299106/38772016-49636eb0-3ffb-11e8-8630-42ec716d0502.png)

I'm not sure exactly what set of circumstances causes the rendering issue, as I have a second portal set up with the sky blocks directly behind it without issue, along with another block nearby for testing.

![2018-04-14_15 37 30](https://user-images.githubusercontent.com/5299106/38772044-ad3ebcfa-3ffb-11e8-9c5c-b34a5fccbdb6.png)

The issue does appear to have some relation to chunk boundaries, as when I enter the chunk that the single sky block is in, the rendering stops functioning correctly.

![2018-04-14_15 37 35](https://user-images.githubusercontent.com/5299106/38772052-ee1336ca-3ffb-11e8-945b-deedd0908528.png)

Again, this is only while the sky block that seems to be causing the issue is in view, as being in the same spot but not looking at it allows the portal rendering to function properly.

![2018-04-14_15 39 25](https://user-images.githubusercontent.com/5299106/38772056-09c82376-3ffc-11e8-91bb-a20b31869f99.png)

Let me know if you need any other information.

**Comment by Buuz135** [comment]
I dont think I can do much, It might be on OpenBlocks side breaking transparent textures

**Comment by Buuz135** [comment]
Should be fixed the next version
