### ISSUE TITLE
Portality Controller crashes the game.

### ISSUE THREAD

**Issue by TwiiCe** [Buuz135/Portality#22]
Hey! I'm planning on using Portality in my modpack (misconduct), and making it one of the ways of transporting players between worlds. (Can this double as asking for permission?)

Can you help me with the following crash report?

-- Head --
Thread: Server thread
Stacktrace:
	at com.buuz135.portality.util.TeleportUtil.teleportEntityInterdimentional(TeleportUtil.java:128)
	at com.buuz135.portality.util.TeleportUtil.handleEntityTeleport(TeleportUtil.java:88)
	at com.buuz135.portality.util.TeleportUtil.teleportEntity(TeleportUtil.java:47)
	at com.buuz135.portality.handler.TeleportHandler.tick(TeleportHandler.java:65)
	at com.buuz135.portality.tile.TileController.func_73660_a(TileController.java:69)

-- Block entity being ticked --
Details:
	Name: portality:controller_tile // com.buuz135.portality.tile.TileController
	Block type: ID #979 (tile.portality:controller // com.buuz135.portality.block.BlockController)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-25,80,-3), Chunk: (at 7,5,13 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #979 (tile.portality:controller // com.buuz135.portality.block.BlockController)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

I've no idea how I've caused this, but every time I try to start up the world, it will crash.
If you want, I can send you a copy of the world. Let me know.

**Comment by Buuz135** [comment]
Which version of forge and of the mod are you using?

**Comment by TwiiCe** [comment]
MC 1.12.2 - Forge-14.23.2.2654

Portality-1.12.2-1.0.3-4

**Comment by TwiiCe** [comment]
I've gone ahead and restarted the game.

While it took a little longer to crash me, it still did.

Pastebin of the crash: https://pastebin.com/P1akNhiX

**Comment by Buuz135** [comment]
Have you tried in the latest version?

**Comment by TwiiCe** [comment]
Yes. The pastebin link is the latest log.

**Comment by Buuz135** [comment]
No, I mean the latest version of the mod. 🤔

**Comment by TwiiCe** [comment]
Yes. I have upodated and restarted. The pastebin log is with your latest release.

**Comment by Buuz135** [comment]
Does it happen all the time?

**Comment by TwiiCe** [comment]
Yes. I start the game and it happens.

**Comment by TwiiCe** [comment]
Feel free to add me on Discord, I have a feeling communication on there will be a little easier.

**Comment by Buuz135** [comment]
I just downloaded the pack, and used the portal to go to the nether and works fine.

**Comment by TwiiCe** [comment]
The pack is fine, its my local version (where im building the actual pack) where it crashes. 
Could it have issues with teleporting to different dimensions (IE, Dimension 6, Aroma1997's Mining world)

**Comment by Buuz135** [comment]
Maybe its another mod messing it up

**Comment by TwiiCe** [comment]
Maybe, but the crashlog clearly states 

-- Block entity being ticked --
Details:
Name: portality:controller_tile // com.buuz135.portality.tile.TileController
Block type: ID #979 (tile.portality:controller // com.buuz135.portality.block.BlockController)

So I kind of doubt it. I can verify by removing the mod, and seeing if the problem persists.

**Comment by Buuz135** [comment]
Having a mod in the crashlog doesnt mean that its 100% the mod fault, you should check what have you changed between version to see what did mess up the Acces Transformers

**Comment by TwiiCe** [comment]
Ive disabled Portality, this fixed the crash.
I'm afraid that this is a portality problem.

**Comment by Buuz135** [comment]
I repeat, something have messed up Access Transformers, check what have you done between the released version and your dev version to check what did break it

**Comment by TwiiCe** [comment]
I've no idea what you mean with Access Transformers. Thats just me not being a coder. 
I take it that there's no easy fix for this, I might have to look elsewhere for transportation.

Thanks for taking your time trying to solve this.

**Comment by Buuz135** [comment]
CHECK WHAT YOU HAVE CHANGE BETWEEN VERSIONS AND UNDO EVERY STEP TO FIGURE OUT WHAT DID MESS UP THING. I have told you that 3 times ... please read ...

**Comment by TwiiCe** [comment]
Hey Buuz, 

In the beta I havent used the portality at all. I've only placed blocks. There's no use in seeing what I changed, as this error occured the first time I tried to use the mod.

> CHECK WHAT YOU HAVE CHANGE BETWEEN VERSIONS AND UNDO EVERY STEP TO FIGURE OUT WHAT DID MESS UP THING.
I made a portality portal to Aroma1997's mining world, built a maze and crashed after a few minutes of inactivity.
I'm sorry if I cant explain it well enough, English isn't my native language. I'm also not a mod developer, so I've no idea what I'm looking at or what I can do to help you better.

Previous versions don't differ from this version, except for the fact that this version has an active portal. It's the first thing I did when I continued work on Misconduct.

**Comment by TwiiCe** [comment]
Alright, I've tried something else. In MCEdit I removed the controllers form the portality portal. After I loaded the game back up, everything seems fine again.

Let's hope its a random occurrence. I'll keep you updated.
