### ISSUE TITLE
Provide some details on chunk loading

### ISSUE THREAD

**Issue by ZXQWAS** [Buuz135/Portality#33]
Could you provide some details on how chunk loading should work with portality please? Do the portals keep their chunks loaded, only entrance chunk, only when activated, etc? If I have to put a chunk loader to keep a portal remotely powered via RF input/output block, do I need to put it only for the head chunk or for the entire portal? Can I actually use the RF output block to directly power the portal controller block, in the same portal? I think I had to add a fluxduct for this to work, even when they were directly connected (for some reason I used a capacitor in the end anyway)? I believe stuff like this should be put at some visible place.

**Comment by Buuz135** [comment]
Portal Controllers keep they chunk loaded when they are running
