### ISSUE TITLE
Portal List Maxing At 8

### ISSUE THREAD

**Issue by JaredTheRedd** [Buuz135/Portality#47]
I've been playing Project Ozone 3, and have run into an issue with this mod. So, I am creating my 10th portal, but once I travel through it, it does not show up in my portal list when I try to call a portal. I can go back to where I placed the portal and call another portal with it, but I cannot use another portal to call this one.

I don't think this is intended, so I figured I would report it as a bug. The portal list won't show more than 8 portals

**Comment by Buuz135** [comment]
If the portals aren't appearing in the other side it might be because of distance, the interdimensional module makes it infinite, maybe the other side doesn't have it
