### ISSUE TITLE
Max distance

### ISSUE THREAD

**Issue by AntoineABI** [Buuz135/Portality#53]
Hello this undocumented but I created two portal and I can not dial because max distance is 600. How to increase it? Do I have to add a inter-dimensional module to ignore distance? I try to put more row of portal block but without success....

Thanks for the good work nonetheless. The portals look fantastic!

**Comment by Buuz135** [comment]
The longer the portal the further you can travel

**Comment by AntoineABI** [comment]
Like I said doc.
And when you add rows you have to break and replace a former block so the portal update to the new length ;)
At the end that a tremendous amount of quartz!!!
