### ISSUE TITLE
1.14.4 Interdimensional Portal fails

### ISSUE THREAD

**Issue by Yamza** [Buuz135/Portality#54]
When using a portal in the end to go to the overworld, you get shot out of the portal into the void instead of teleporting.

forge-28.0.49
Portality-1.14.4-2.0.14.jar
titanium-2.1.58.jar

Log: https://hatebin.com/nmnqobiudt

Similar to https://github.com/Buuz135/Portality/issues/50

**Comment by Buuz135** [comment]
Fixed in released version 2.0.4
