### ISSUE TITLE
Portal blocks do not drop when broken

### ISSUE THREAD

**Issue by Yamza** [Buuz135/Portality#55]
Error showing on server when blocks are placed: https://hatebin.com/joqssjvrzq
https://drive.google.com/open?id=1kMegRXR-ZY6C_I822F4kSyfu_Gf1p9LD

Also, the portal doesn't work when fully formed.

Forge 28.0.51
Modlist: https://i.imgur.com/iQwN33d.png

**Comment by Buuz135** [comment]
Should be fixed in https://www.curseforge.com/minecraft/mc-mods/portality/files/2783106
