### ISSUE TITLE
[1.14.4] Portals call list empty

### ISSUE THREAD

**Issue by BourotBenjamin** [Buuz135/Portality#60]
The documentation in not very clear so I'm not sure if I'm doing it right or if I'm missing somethin but : 
I created a new signel player creative world.
I built a portal and Add an energy module and a generator to power the portal.
FE are going to max so That part works ( but you shold explain in the docs that the mod contains a generator and how to craft it / use it ).

Built another portal a few blocs away.

I can change the portal name.
I can get the call list by clicking the "Call Portal" button.
The other buttons don't do anything.

In it's status it says 'Links: Inactive'.

PS : I think it could also be great to improve the manual. Add the portal recipes, Add the modules and a descriptions of what they do, a manual to how to make it works. ( If you want to di it fats, just a vidéo from you setting up two portals and connecting them for exemple), ...

Thanks.

**Comment by Buuz135** [comment]
Fixed in released version 2.0.4
