### ISSUE TITLE
[1.15.1][bug] Crash on game launch

### ISSUE THREAD

**Issue by Foreverthen** [Buuz135/Portality#68]
cannot launch game with portality loaded. Crash log follows below.
--------------
https://pastebin.com/ngiv8Y6e

(edit 1: pastebin... soz forgot)

**Comment by drizzs** [comment]
pastebin next time :( this is terrible to read!

**Comment by Foreverthen** [comment]
https://pastebin.com/vdwNB0vR - debug.log

**Comment by waddon1** [comment]
It's also crashing on launch for me

**Comment by Tsoccerguy3** [comment]
This is easier to read , Portality and Titanium crash debug log
[debug.zip](https://github.com/InnovativeOnlineIndustries/Portality/files/4048863/debug.zip)
