### ISSUE TITLE
[1.14.4] Portality Portals remove existing chunkloading when closed

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/Portality#69]
Portality portals removes [persistent bits](https://github.com/oitsjustjose/Persistent-Bits) forceloaded chunks, from what I know the current version of persistent bits uses /forceload commands to chunkload, however for some reason after activating a Portality portal, the chunk that the Portal Controller is in will be removed from forceload

It seems that the mod removes the chunk the portal controller is in when it is not dialed/running, hence if you hit "dial once" it will remove the chunk from the forceload list

### Versions
- portality-1.14.4-2.0.4-b0b3467
- titanium-1.14.4-2.2.10
- PersistentBits-1.14.4-2.0.2
- Forge 28.1.109

Original issue: https://github.com/NillerMedDild/Enigmatica4/issues/252

**Comment by Buuz135** [comment]
Currently only the 1.16 version is supported
