### ISSUE TITLE
Random crashes caused by portal sound?

### ISSUE THREAD

**Issue by Fenekhu** [Buuz135/Portality#75]
I was playing with a friend over lan trying to make a portality portal when his game suddenly crashed. After he restarted and got back in, a few minutes later the same thing happened. He sent me the crash reports and they were both the same thing. [https://pastebin.com/DkHNsCuN](crash report). It seems it has something to do with the sound its making? I'm hosting the world and I'm not crashing but he was doing something completely unrelated and has been crashing. Playing on project ozone 3. forge version 14.23.5.2854, portality version 1.2.3-15.

EDIT: it seems to crash him whenever a portal closes. I had another friend on for a while and I don't think it crashed him.

**Comment by Buuz135** [comment]
Currently only the 1.16 version is supported
