### ISSUE TITLE
[crash bug] [dedicated server] [1.15.2] Connection issues between the End and any other dimension.

### ISSUE THREAD

**Issue by Ruchian** [Buuz135/Portality#78]
I discovered the issue while playing on the MMD Public (dedicated) Server
which currently runs the modpack RAM- Really Awesome mods, version 0.4.4
which contains: Portality 2.1.2 aaa27f and runs on Forge 31.2.27

I noticed for some reason a portality portal placed in the end doesn't work. (The portal's controller block is powered by the low efficiency generator provided by the Portality mod and I noticed the size and length of the portal didn't matter)
 (yes, the portal has a interdimensional upgrade block in its frame, like all other portals I made. It's just this specific portal next to the End arrival (obsidian) platform I placed which doesn't work. )
The portal won't dial to any portal. It can however be dialed to from anywhere.
I tried changing its location, rebuilding it, it seemed to be the End I thought, which caused the portal to become bugged.

When you dial a portal with this portal (in the end), you can't use it since it doesn't activate. (you can arrive at the portal from any portal, but cannot go back). When the bugged portal in the end was used to try and dial to any portal (in the overworld for example), nothing seems to happen, however I suspect that it still attempts to connect to a portal. When you exit the end and go to the set target portal, no connection appears to have been established. However, when you try to interact with the portal controller there and dial another portal (or the very portal in the end), not long later the server will crash.

The admin of the server has been friendly enough to provide the crash report.
https://gist.github.com/ProxyNeko/5bbbad4daf54724ad36b4857ec79ea4c

I haven't run into any other issues with the mod on the pack. Portal traveling between the Mining Dimension (provided by YAMDA) seems to work as normal. 

Curious enough I decided to do some deeper testing. Suspecting the issue is repeatable with just Portality as sole mod on a dedicated server (well + Titanium  xd), I decided to test it deeply. What I found out is that it indeed is a bug that solely lies with Portality and it is repeatable.
(I tested it on Forge 31.2.31 using the same portality mod (2.1.2-aaa257f) and titanium 2.4.2)

I discovered that for some reason the portal becomes glitched when you travel to another dimension after using a portal. It is the portal that you last used (the one you used to call a portal) that becomes permanently glitched. For some odd reason the location itself becomes glitched. so the portal needs to be moved pretty far to avoid having a glitched portal.
 When you try to dial with a glitched portal, nothing happens. When you then try to dial with the portal you tried to dial to earlier, the server crashes.
This happens due to a tick taking 60 seconds.
[Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog/]: A single server tick took 60.00 seconds (should be max 0.05)
[Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog/]: Considering it to be crashed, server will forcibly shutdown.
;p

The crash is the same. The report is different due to less mods, but yeah. You can test it out yourself if you want to.

**Comment by Buuz135** [comment]
Currently only the 1.16 version is supported
