### ISSUE TITLE
[1.16.1] Won't load on latest version of Forge.

### ISSUE THREAD

**Issue by Gbergz** [Buuz135/Portality#81]
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.97
**Titanium Version:** 3.0.2
**Portality Version:** 3.0.0-58d8eb5

**Logs:** https://hastebin.com/ixaxanehuz.sql

**Screenshot:** 
![image](https://user-images.githubusercontent.com/26634554/88799450-cea64180-d1a6-11ea-8da9-4674eaa0e9ee.png)

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Portality/commit/76fb3591ca41f8c7ca6c78eeb564af410a56007b
