### ISSUE TITLE
Crash while Scrolling

### ISSUE THREAD

**Issue by Ravin890** [Buuz135/Portality#82]
So if you are in the 'Call Portal' GUI and you use your mouse wheel to scroll the game will crash. I am not sure what would happen if you have more than 6 portals but client will close due to you scrolling.

Version of Minecraft: 1.15.2
Version of Forge: 31.2.36
Version of Portality: 1.15.2-2.1.2-aaa257f
Version of Titanium: 1.15.2-2.4.2

[crash-2020-08-06_23.56.11-client.txt](https://github.com/InnovativeOnlineIndustries/Portality/files/5039252/crash-2020-08-06_23.56.11-client.txt)

**Comment by MelanX** [comment]
Just as notification, GitHub didn’t close this issue @Buuz135
