### ISSUE TITLE
[1.12.2] Other players can close portals

### ISSUE THREAD

**Issue by Vulant** [Buuz135/Portality#90]
I am not sure if I just didn't set this up right or not, but when I create a portal, other players can close the portal even though they don't own it. When I set the portal to private, they can still close the portal that is linked. I even tried putting on the creative module, and I can still replicate the issue. 

Edit: After further testing, if it's forced and private, then while someone else is also in creative, they cannot close the portal, but oddly enough in survival they can.
Same if it is not forced and private.

Did I do something wrong or is this a bug?

**Comment by Buuz135** [comment]
Currently only the 1.16 version is supported
