### ISSUE TITLE
Portals stop working when copying/pasting with WorldEdit

### ISSUE THREAD

**Issue by AsixJin** [Buuz135/Portality#94]
I created a portal and attempted to copy/paste it using WorldEdit, but when I paste the new portal it breaks and throws the invalid portal structure error. I can't get the pasted portal to work even if I remove some blocks and replace them.

**Comment by Adrigorithm** [comment]
WorldEdit isn't intended to work with any mods. Anything more complex than a decoration block can break when moved. I seriously doubt the dev will/can do anything about this.

**Comment by AsixJin** [comment]
That's unfortunate...Thanks!
