### ISSUE TITLE
[1.16.3] NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by manmaed** [Buuz135/Portality#96]
I have no idea what casued this but here is a crash report:

**Crash Repot**
https://pastebin.com/RMTNK2bQ

**Latest Log**
https://pastebin.com/dKZUrmhX

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Portality/commit/669d31b6096d98df9c0df8e055e80a83ec288b8f
