### ISSUE TITLE
Crashes on startup depending on network availability. Direwolf20 1.6.4 pack

### ISSUE THREAD

**Issue by ST92** [Buuz135/Portality#98]
Portality Version: 3.2.0

Crashlog If Applicable (Upload to pastebin/gist): https://pastebin.com/CrywvZDw

What also broke: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/980

Crashes on startup. When I disconnect network it starts up OK.

**Comment by Buuz135** [comment]
Fixed https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/bc051fa987e23f698e1c40af4a88c340b8504447 plese restart
